WVSF-7  Add Doc converter to showcase
PDFTron/salesforce-pdf-app pull request #7
Opened 2022-03-08 21:45 UTC by Swoshua

- added exportfile lwc
- methods for file conversion

2022-03-22 20:58 UTC, tommywintersr requested changes
Pls review requested change (label change on the doc conversion drop down) + can you do a quick sweep for `console.log()` and remove them as well please? Thanks!

2022-03-22 20:58 UTC, tommywintersr commented on .sfdx/sfdx-config.json
> +  "defaultusername": "jlore@curious-moose-15goth.com"
Please add to `.gitignore`, otherwise it will automatically set your org as the default users for anyone cloning the repo

ie
```
# .gitignore in project root
.sfdx/
```

2022-03-22 20:58 UTC, tommywintersr commented on .sfdx/sfdx-config.json
> +  "defaultusername": "jlore@curious-moose-15goth.com"
same for [force-app/main/.DS_Store](https://github.com/PDFTron/salesforce-pdf-app/pull/7/files#diff-e110d4719de7535e026be22dd18350e85e5930b13ee90b18a971529b638226d0)


Here's a simple .gitignore file you can use:
```
# General
.DS_Store
.AppleDouble
.LSOverride

# Thumbnails
._*

# these resources are maintained manually
force-app/main/default/staticresources/full
force-app/main/default/staticresources/lean
force-app/main/default/staticresources/asmFull
force-app/main/default/staticresources/asmLean
force-app/main/default/staticresources/lib
force-app/main/default/staticresources/resource
force-app/main/default/staticresources/office
force-app/main/default/staticresources/officeResource
force-app/main/default/staticresources/external

.sfdx/
.vscode/
node_modules
```

2022-03-22 20:58 UTC, tommywintersr commented on force-app/main/default/lwc/exportFile/exportFile.js
> +        { label: 'PNG', value: 'png' }
@Swoshua  can you add to the `label` here to indicate it will convert to multiple files for multipage docs? ie `PNG (one file per document page)`

2022-03-22 20:58 UTC, tommywintersr commented on force-app/main/default/lwc/exportFile/exportFile.js
> +        { label: 'PNG', value: 'png' }
@Swoshua  can you add to the `label` here to indicate it will convert to multiple files for multipage docs? ie `PNG (one file per document page)`

2022-03-23 15:40 UTC, Swoshua commented on .sfdx/sfdx-config.json
> +  "defaultusername": "jlore@curious-moose-15goth.com"
there already is a .gitignore file

2022-03-24 17:21 UTC, tommywintersr approved these changes
Thanks Josh, looks good!

2022-03-24 17:21 UTC, merged